Update button usage guidelines
primer/design pull request #132
Opened 2020-12-14 23:20 UTC by ashygee

This PR updates our current [button usage guidelines](https://primer.style/design/ui-patterns/button-usage) and with more specific guidelines and updated screenshots.

2020-12-15 16:15 UTC, colebemis reviewed
You might be getting errors because `img` tags need to be self-closing (i.e. `<img ... />` not `<img ...>`)

2020-12-15 16:15 UTC, colebemis commented on content/ui-patterns/button-usage.mdx
> +<img width="188" alt="Primary button has a green background and white text" src="https://user-images.githubusercontent.com/10384315/102147130-19a3b700-3e1f-11eb-8581-3b58b053dadd.png">
```suggestion
<img width="188" alt="Primary button has a green background and white text" src="https://user-images.githubusercontent.com/10384315/102147130-19a3b700-3e1f-11eb-8581-3b58b053dadd.png" />
```

2020-12-15 16:15 UTC, colebemis commented on content/ui-patterns/button-usage.mdx
> +<img width="188" alt="Secondary button has light gray background and dark gray text" src="https://user-images.githubusercontent.com/10384315/102147132-19a3b700-3e1f-11eb-9cc9-0c7a6fdb8e4a.png">
```suggestion
<img width="188" alt="Secondary button has light gray background and dark gray text" src="https://user-images.githubusercontent.com/10384315/102147132-19a3b700-3e1f-11eb-9cc9-0c7a6fdb8e4a.png" />
```

2020-12-15 16:15 UTC, colebemis commented on content/ui-patterns/button-usage.mdx
> +<img width="188" alt="Outline button has light gray background and blue text" src="https://user-images.githubusercontent.com/10384315/102147129-19a3b700-3e1f-11eb-94b7-941c140701e3.png">
```suggestion
<img width="188" alt="Outline button has light gray background and blue text" src="https://user-images.githubusercontent.com/10384315/102147129-19a3b700-3e1f-11eb-94b7-941c140701e3.png" />
```

2020-12-17 14:11 UTC, yaili requested changes
I think the **Anatomy**, and each of the sections in **Variations** should have an image.

2021-08-18 21:53 UTC, colebemis commented
Closing this since there are a lot of conflicts with @mperrotti's recent update to the button docs. @ashygee feel free to reopen if there are still changes you'd like to make.

2021-08-18 21:53 UTC, closed without merging