Button component interface guidelines
primer/design pull request #193
Opened 2021-11-10 07:57 UTC by pksjce

Took a quick stab at distilling my research at https://github.com/github/primer/issues/382 to a button component guideline here. Thanks @ashygee for all the figma files!

Seeking feedback and help for the following stuff

- [ ] Is this a good addition? What do you think of the tone and information in the post? I tried to go off of other documents in the components section.
- [ ] A separate component for ButtonLink. Thoughts?
- [ ] Removal of Outline button and large size buttons. What about the icon sizes though?

![Screen Shot 2021-11-10 at 6 56 45 pm](https://user-images.githubusercontent.com/417268/141072787-4ca0c29e-bd12-40aa-bd6c-bfef33dd8a8d.png)

cc - @langermank @simurai @ashygee

2021-11-10 11:02 UTC, yaili requested changes
👋🏼  Thanks for starting this! I've added a bunch of comments, suggestions, and pings for other folks to chime in. Can you convert this to draft, as it still needs a bunch of edits before we're ready?

**Update:** Oops, forgot to say this is the file to update the nav - https://github.com/primer/design/blob/master/src/%40primer/gatsby-theme-doctocat/nav.yml

2021-11-10 11:02 UTC, yaili commented on content/components/button.mdx
> +The Button component has to follow below criteria to be accessible
@alliethu can you review this section? And also consider if this is the best place for this info to be.

2021-11-10 11:02 UTC, yaili commented on content/components/index.mdx
> +    <div>
This should be after action list to keep a-z order. Needs image and updated description.

2021-11-12 03:51 UTC, pksjce commented on content/components/button.mdx
> +<Box sx={{fontSize: 3}} class="lead" as="p">
Is there one I can use for this? I mostly copied the structure from the Tokens page since thats the latest among the components.

2021-11-12 04:57 UTC, pksjce commented on content/components/button.mdx
> +In components, this is represented by the `variant` prop.
Got it. Will modify

2021-11-12 04:58 UTC, pksjce commented on content/components/button.mdx
> +The default button is the default variant in the `Button` component.
Well its the most commonly used variant. I could mention that.

2021-11-12 05:01 UTC, pksjce commented on content/components/button.mdx
> +The default button is the default variant in the `Button` component.
yep! adding some descriptions.

2021-11-12 05:05 UTC, pksjce commented on content/components/button.mdx
> +We use the `CounterLabel` component to show this.
Nope removing this implementation detail

2021-11-12 05:09 UTC, pksjce commented
Thanks so much for your inputs @yaili ! This is shaping so well. Look forward to our meeting next week.

2021-11-12 08:44 UTC, simurai reviewed
> Is this a good addition?

Yessss.. 💯  I think sooner or later all components should have a page like this one. For new components maybe even before implementation starts. I see it as the "source of truth" across all Primer libraries.

2021-11-12 08:44 UTC, simurai commented on content/components/button.mdx
> +        src="https://user-images.githubusercontent.com/10384315/138380981-2b8b719d-919f-4a24-94b3-573c3d4025d5.png"
Yeah, I think they would need to be exported as `2x` (for retina displays). They also seem to have rounded corners and spacious padding:

![image](https://user-images.githubusercontent.com/378023/141435587-5f3bdbb5-69fe-4d6c-b4f9-5ae6f7ea0ad1.png)

Maybe we could create a template that uses Frames in Figma so it's easy to re-export after making changes.

2021-11-12 08:44 UTC, simurai commented on content/components/button.mdx
> +A counter in the trailing position is a common pattern at Github. Buttons can denote state by changing icon color or text.
```suggestion
A counter in the trailing position is a common pattern at GitHub. Buttons can denote state by changing icon color or text.
```

2021-11-12 08:44 UTC, simurai commented on content/components/button.mdx
> +Button components will be available in two sizes.
```suggestion
Button components are available in two sizes.
```

And might be nice to also show an image.

2023-12-12 21:29 UTC, closed without merging