Add text resize, respacing and zoom doc page
primer/design pull request #226
Opened 2022-03-09 20:38 UTC by khiga8

Resolves https://github.com/github/accessibility/issues/804

2022-03-09 22:45 UTC, khiga8 commented on content/accessibility/text-resize-and-respacing.mdx
> +
Hey @langermank and @vdepizzol! I heard that you're doing work related to Primer font-size conversion to REM system. Is there any guidance you think we should offer here to designers and developers meanwhile?

2022-03-10 00:28 UTC, inkblotty reviewed
Can we make some of the useful `alt` text a caption for sighted users who may not know what's significant about the image?

2022-03-10 00:28 UTC, inkblotty commented on content/accessibility/text-resize-and-respacing.mdx
> +    <img width="600" alt="Screenshot of a GitHub issue description where the container has a fixed height, causing the authored long description to overflow out of bounds" src="https://user-images.gi
In these images, the detailed description in the Alt text could be useful for sighted people too. Can we add to the Caption? For example:
`Don't use a fixed height on text content containers. In the image below, you can see that the fixed height of the container causes it to overflow out of bounds.`

2022-03-10 11:41 UTC, yaili requested changes

2022-03-10 11:41 UTC, yaili commented on content/accessibility/text-resize-and-respacing.mdx
> +When sites are built without adequate responsivity considerations (e.g. setting fixed width and height, using non-relative font sizing), sites may become completely unreadable
```suggestion
When sites are built without adequate responsivity considerations (for example: setting fixed width and height, using non-relative font sizing), sites may become completely unreadable 
```

Is _responsivity_ a word?

2022-03-10 11:41 UTC, yaili commented on content/accessibility/text-resize-and-respacing.mdx
> +Most modern browsers support full-page zoom, while some (e.g. FireFox) also support text-only zoom. While WCAG does not specify how text should be resized, it is best practice for your
```suggestion
Most modern browsers support full-page zoom, while some also support text-only zoom (for example: Firefox). While WCAG does not specify how text should be resized, it is best practice for your 
```

2022-03-10 11:41 UTC, yaili commented on content/accessibility/text-resize-and-respacing.mdx
> +Test your page by using browser zoom with magniciation of up to 200%. Observe that the text content does not overflow, overlap, or become truncated, and that interactive controls still work.
```suggestion
Test your page by using browser zoom with magnification of up to 200%. Confirm that the text content does not overflow, overlap, or become truncated, and that interactive controls still work.
```

2022-03-10 11:41 UTC, yaili commented on content/accessibility/text-resize-and-respacing.mdx
> +#### Text spacing
```suggestion
### Text spacing
```

2022-03-10 11:41 UTC, yaili commented on content/accessibility/text-resize-and-respacing.mdx
> +Observe that text is contained within the bounds of it's container without overlapping or being cutoff.
```suggestion
Confirm that text is contained within the bounds of its container without overlapping or being cutoff.
```

2022-03-10 17:43 UTC, khiga8 commented
@inkblotty, @yaili thank you for the thorough review 🙇‍♀️

2022-03-10 18:43 UTC, yaili approved these changes
👍🏼

2022-03-10 19:12 UTC, merged