update generic link text guidance
primer/design pull request #272
Opened 2022-06-27 19:31 UTC by khiga8

Closes: https://github.com/github/accessibility/issues/1343 (staff-only link)

This PR updates the link guidance with more guidance around generic link text and techniques. 

Updating this to make sure we document the discussions we've been having on Slack and this [recommended guidance in a recent GitHub issue](https://github.com/github/accessibility/issues/1291#issuecomment-1159088348) (staff-only link).

2022-06-28 10:01 UTC, yaili requested changes

2022-06-28 10:05 UTC, owenniblock approved these changes
Minor niggle otherwise looks good 👍

2022-06-28 10:05 UTC, owenniblock commented on content/accessibility/links.mdx
> +## Link text
Suggest a slightly more descriptive title here:

```suggestion
## Writing link text
```

2022-06-28 10:05 UTC, owenniblock commented on content/accessibility/links.mdx
> +- Check a link's purpose. If you can't get an idea of where a link will take you based on the link text alone, the link text should be updated. Learn more at [Link text](#link-text).
Related to my suggestion to change the title below.

```suggestion
- Check a link's purpose. If you can't get an idea of where a link will take you based on the link text alone, the link text should be updated. Learn more at [Writing link text](#writing-link-text).
```

2022-06-28 18:58 UTC, ichelsea commented on content/accessibility/links.mdx
> +- Check a link's purpose. If you can't get an idea of where a link will take you based on the link text alone, the link text should be updated. Learn more about [link text](#link-text).
```suggestion
- Check a link's purpose. If you can't get an idea of where a link will take you based on the link text alone, the link text should be updated. [Learn how to write good link text](#writing-link-text).
```

2022-06-28 19:06 UTC, khiga8 commented on content/accessibility/links.mdx
> +As demonstrated in the examples, this technique adds more complexity to the code and can introduce more problems than it solves so only use this technique if absolutely necessary.
ooh I only saw examples that use screenshots. thanks for the link using a code example.

2022-06-30 00:27 UTC, khiga8 commented on content/accessibility/links.mdx
> +As demonstrated in the examples, this technique adds more complexity to the code and can introduce more problems than it solves so only use this technique if absolutely necessary.
maybe we should introduce linters against, "bad", "good", and emojis.

2022-06-30 00:28 UTC, khiga8 commented
thank you for your feedback @yaili ! mind another review?
I converted the examples to use the DoDont container and got rid of the emojis/banned words.

2022-06-30 20:19 UTC, yaili approved these changes
Thank you! 😊

2022-06-30 20:32 UTC, merged

2024-09-11 03:12 UTC, Duytran889889 reviewed
Hhdjjd

2024-09-11 03:12 UTC, Duytran889889 commented on content/accessibility/links.mdx
> -### Bad: Accessible name results in badly formed sentence 👎
Hsndn d đn
[Uploading guide (1).pdf…]()