Replace broken link with the working one
primer/design pull request #593
Opened 2023-09-17 20:25 UTC by DDKatch

2023-09-17 21:05 UTC, camertron requested changes
Let's link to /css instead.

2023-09-17 21:05 UTC, camertron commented on content/guides/development/rails/index.mdx
> +In addition to the dependencies declared in the `gemspec`, Primer ViewComponents assumes the presence of [Primer CSS](https://primer.style/css/storybook/?path=/docs/gettingstarted--docs).
```suggestion
In addition to the dependencies declared in the `gemspec`, Primer ViewComponents assumes the presence of [Primer CSS](https://primer.style/css).
```

2023-09-18 09:18 UTC, DDKatch commented on content/guides/development/rails/index.mdx
> +In addition to the dependencies declared in the `gemspec`, Primer ViewComponents assumes the presence of [Primer CSS](https://primer.style/css/storybook/?path=/docs/gettingstarted--docs).
@camertron done ✅

2023-09-19 17:07 UTC, camertron approved these changes

2023-09-19 17:07 UTC, merged